# Use for running an Appsmith, during development.

version: "3"

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce:release
    container_name: appsmith
    ports:
      - "8080:80"
    environment:
      APPSMITH_ENCRYPTION_PASSWORD: jCUsttd3ynGFZEb2NYP9
      APPSMITH_ENCRYPTION_SALT: jCUsttd3ynGFZEb2NYP9
    volumes:
      - ./stacks:/appsmith-stacks
